Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# read data from previous example

sjodatos =pd.read_pickle("datos/SJO-pasajeros.pickle")
sjodatoscuadro = sjodatos.unstack()
sjodatoscuadro['extranjeros'].round(1)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_2664/2695622642.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# read data from previous example[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [0msjodatos[0m [1;33m=[0m[0mpd[0m[1;33m.[0m[0mread_pickle[0m[1;33m([0m[1;34m"datos/SJO-pasajeros.pickle"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [0msjodatoscuadro[0m [1;33m=[0m [0msjodatos[0m[1;33m.[0m[0munstack[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0msjodatoscuadro[0m[1;33m[[0m[1;34m'extranjeros'[0m[1;33m][0m[1;33m.[0m[0mround[0m[1;33m([0m[1;36m1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\io\pickle.py[0m in [0;36mread_pickle[1;34m(filepath_or_buffer, compression, storage_options)[0m
[0;32m    194[0m     """
[0;32m    195[0m     [0mexcs_to_catch[0m [1;33m=[0m [1;33m([0m[0mAttributeError[0m[1;33m,[0m [0mImportError[0m[1;33m,[0m [0mModuleNotFoundError[0m[1;33m,[0m [0mTypeError[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 196[1;33m     with get_handle(
[0m[0;32m    197[0m         [0mfilepath_or_buffer[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    198[0m         [1;34m"rb"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\io\common.py[0m in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    709[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    710[0m             [1;31m# Binary mode[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 711[1;33m             [0mhandle[0m [1;33m=[0m [0mopen[0m[1;33m([0m[0mhandle[0m[1;33m,[0m [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    712[0m         [0mhandles[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mhandle[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    713[0m [1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'datos/SJO-pasajeros.pickle'
FileNotFoundError: [Errno 2] No such file or directory: 'datos/SJO-pasajeros.pickle'

