Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pd.options.plotting.backend = "plotly"

NP = pd.read_stata('datos/NelsonPlosserData.dta', index_col='year')
NP.index = NP.index.year

# modelo de salarios nominales
lwg = NP[['lwg']].dropna()
lwg['DL'] = (lwg.index > 1929).astype(int)
lwg['DP'] = (lwg.index == 1930).astype(int)
lwg['t'] = np.arange(lwg.shape[0])
lwg['Ly'] = lwg['lwg'].shift(1)
model1_lwg = ols('lwg~ DL + DP + t + Ly', lwg).fit()
model2_lwg = ols('lwg~ DL + t ', lwg).fit()

lwg['Ajuste'] = model2_lwg.fittedvalues

lwg[['lwg', 'Ajuste']].plot()

#title='Salarios nominales'
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_23076/4153920555.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mpd[0m[1;33m.[0m[0moptions[0m[1;33m.[0m[0mplotting[0m[1;33m.[0m[0mbackend[0m [1;33m=[0m [1;34m"plotly"[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [0mNP[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_stata[0m[1;33m([0m[1;34m'datos/NelsonPlosserData.dta'[0m[1;33m,[0m [0mindex_col[0m[1;33m=[0m[1;34m'year'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [0mNP[0m[1;33m.[0m[0mindex[0m [1;33m=[0m [0mNP[0m[1;33m.[0m[0mindex[0m[1;33m.[0m[0myear[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\io\stata.py[0m in [0;36mread_stata[1;34m(filepath_or_buffer, convert_dates, convert_categoricals, index_col, convert_missing, preserve_dtypes, columns, order_categoricals, chunksize, iterator, compression, storage_options)[0m
[0;32m   1939[0m ) -> DataFrame | StataReader:
[0;32m   1940[0m [1;33m[0m[0m
[1;32m-> 1941[1;33m     reader = StataReader(
[0m[0;32m   1942[0m         [0mfilepath_or_buffer[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1943[0m         [0mconvert_dates[0m[1;33m=[0m[0mconvert_dates[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\io\stata.py[0m in [0;36m__init__[1;34m(self, path_or_buf, convert_dates, convert_categoricals, index_col, convert_missing, preserve_dtypes, columns, order_categoricals, chunksize, compression, storage_options)[0m
[0;32m   1089[0m [1;33m[0m[0m
[0;32m   1090[0m         [0mself[0m[1;33m.[0m[0m_native_byteorder[0m [1;33m=[0m [0m_set_endianness[0m[1;33m([0m[0msys[0m[1;33m.[0m[0mbyteorder[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1091[1;33m         with get_handle(
[0m[0;32m   1092[0m             [0mpath_or_buf[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1093[0m             [1;34m"rb"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\ProgramData\Anaconda3\lib\site-packages\pandas\io\common.py[0m in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    709[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    710[0m             [1;31m# Binary mode[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 711[1;33m             [0mhandle[0m [1;33m=[0m [0mopen[0m[1;33m([0m[0mhandle[0m[1;33m,[0m [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    712[0m         [0mhandles[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mhandle[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    713[0m [1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'datos/NelsonPlosserData.dta'
FileNotFoundError: [Errno 2] No such file or directory: 'datos/NelsonPlosserData.dta'

