Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
arma22 = ARMA(phi=[1.3, -0.4], theta=[0.1, -0.3])
arma11 = ARMA(phi=[0.8], theta=[0.6])


merge_plots(
   [arma22.plot_correlogram(18), arma11.plot_correlogram(18), arma22.plot_partial_correlogram(18), arma11.plot_partial_correlogram(18)],
   cols=2,
   subplot_titles=[str(arma22), str(arma11)],
   title_text='Autocorrelaci√≥n (arriba) y autocorrelaci√≥n parcial (abajo)',
)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_12632/806998552.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0marma22[0m [1;33m=[0m [0mARMA[0m[1;33m([0m[0mphi[0m[1;33m=[0m[1;33m[[0m[1;36m1.3[0m[1;33m,[0m [1;33m-[0m[1;36m0.4[0m[1;33m][0m[1;33m,[0m [0mtheta[0m[1;33m=[0m[1;33m[[0m[1;36m0.1[0m[1;33m,[0m [1;33m-[0m[1;36m0.3[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0marma11[0m [1;33m=[0m [0mARMA[0m[1;33m([0m[0mphi[0m[1;33m=[0m[1;33m[[0m[1;36m0.8[0m[1;33m][0m[1;33m,[0m [0mtheta[0m[1;33m=[0m[1;33m[[0m[1;36m0.6[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m merge_plots(

[1;31mTypeError[0m: ARMA() got an unexpected keyword argument 'phi'
TypeError: ARMA() got an unexpected keyword argument 'phi'

