Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys
sys.path.insert(1, DATAPATH)
from mackinnon import MacKinnon  # este m√≥dulo contiene herramientas para calcular valores cr√≠ticos de MacKinnon
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOptionError[0m                               Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m
[0;32m      2[0m sys[38;5;241m.[39mpath[38;5;241m.[39minsert([38;5;241m1[39m, DATAPATH)
[1;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmackinnon[39;00m [38;5;28;01mimport[39;00m MacKinnon

File [1;32m~\OneDrive\Documents\Teaching\econometria\labs\../data\mackinnon.py:7[0m, in [0;36m<module>[1;34m[0m
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mio[39;00m [38;5;28;01mimport[39;00m StringIO
[1;32m----> 7[0m [43mpd[49m[38;5;241;43m.[39;49m[43mset_option[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mprecision[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;241;43m5[39;49m[43m)[49m
[0;32m     11[0m [38;5;66;03m#================================================================================[39;00m
[0;32m     12[0m [38;5;66;03m# MacKinnon 2010 Critical Values for Cointegration Tests[39;00m
[0;32m     13[0m 
[1;32m   (...)[0m
[0;32m     18[0m [38;5;66;03m#    - the number of observations, and[39;00m
[0;32m     19[0m [38;5;66;03m#    - the inclusion of a constant, a linear trend, and a quadratic trend.[39;00m
[0;32m     23[0m nc_table [38;5;241m=[39m StringIO([38;5;124m"""[39m[38;5;124mN,Level,Obs,beta_inf,se,beta1,beta2,beta3[39m
[0;32m     24[0m [38;5;124m1,1[39m[38;5;124m%[39m[38;5;124m,15000,-2.57,0.000110,-2.24,-3.63,0.00[39m
[0;32m     25[0m [38;5;124m1,5[39m[38;5;124m%[39m[38;5;124m,15000,-1.94,0.000074,-0.27,-3.37,31.22[39m
[0;32m     26[0m [38;5;124m1,10[39m[38;5;124m%[39m[38;5;124m,15000,-1.62,0.000059,0.27,-2.71,25.36[39m
[0;32m     27[0m [38;5;124m"""[39m)

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\_config\config.py:256[0m, in [0;36mCallableDynamicDoc.__call__[1;34m(self, *args, **kwds)[0m
[0;32m    255[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds):
[1;32m--> 256[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m[38;5;18m__func__[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\_config\config.py:149[0m, in [0;36m_set_option[1;34m(*args, **kwargs)[0m
[0;32m    146[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124m_set_option() got an unexpected keyword argument [39m[38;5;124m"[39m[38;5;132;01m{[39;00mkwarg[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m'[39m)
[0;32m    148[0m [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m [38;5;28mzip[39m(args[::[38;5;241m2[39m], args[[38;5;241m1[39m::[38;5;241m2[39m]):
[1;32m--> 149[0m     key [38;5;241m=[39m [43m_get_single_key[49m[43m([49m[43mk[49m[43m,[49m[43m [49m[43msilent[49m[43m)[49m
[0;32m    151[0m     o [38;5;241m=[39m _get_registered_option(key)
[0;32m    152[0m     [38;5;28;01mif[39;00m o [38;5;129;01mand[39;00m o[38;5;241m.[39mvalidator:

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\_config\config.py:116[0m, in [0;36m_get_single_key[1;34m(pat, silent)[0m
[0;32m    114[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo such keys(s): [39m[38;5;132;01m{[39;00m[38;5;28mrepr[39m(pat)[38;5;132;01m}[39;00m[38;5;124m"[39m)
[0;32m    115[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(keys) [38;5;241m>[39m [38;5;241m1[39m:
[1;32m--> 116[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124m"[39m[38;5;124mPattern matched multiple keys[39m[38;5;124m"[39m)
[0;32m    117[0m key [38;5;241m=[39m keys[[38;5;241m0[39m]
[0;32m    119[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m silent:

[1;31mOptionError[0m: 'Pattern matched multiple keys'
OptionError: 'Pattern matched multiple keys'

