Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
SJO.index = pd.period_range(start=f"{SJO['AÃ±o'].iloc[0]}-{SJO['Mes'].iloc[0]}", periods=SJO.shape[0], freq='M')
SJO
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\_libs\tslibs\parsing.pyx:362[0m, in [0;36mpandas._libs.tslibs.parsing.parse_datetime_string_with_reso[1;34m()[0m

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\_libs\tslibs\parsing.pyx:570[0m, in [0;36mpandas._libs.tslibs.parsing.dateutil_parse[1;34m()[0m

[1;31mValueError[0m: Unknown datetime string format, unable to parse: 2011-ABRIL

During handling of the above exception, another exception occurred:

[1;31mDateParseError[0m                            Traceback (most recent call last)
Input [1;32mIn [8][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m SJO[38;5;241m.[39mindex [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mperiod_range[49m[43m([49m[43mstart[49m[38;5;241;43m=[39;49m[38;5;124;43mf[39;49m[38;5;124;43m"[39;49m[38;5;132;43;01m{[39;49;00m[43mSJO[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mAÃ±o[39;49m[38;5;124;43m'[39;49m[43m][49m[38;5;241;43m.[39;49m[43miloc[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m-[39;49m[38;5;132;43;01m{[39;49;00m[43mSJO[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mMes[39;49m[38;5;124;43m'[39;49m[43m][49m[38;5;241;43m.[39;49m[43miloc[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mperiods[49m[38;5;241;43m=[39;49m[43mSJO[49m[38;5;241;43m.[39;49m[43mshape[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[43mfreq[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mM[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      2[0m SJO

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\core\indexes\period.py:562[0m, in [0;36mperiod_range[1;34m(start, end, periods, freq, name)[0m
[0;32m    559[0m [38;5;28;01mif[39;00m freq [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m ([38;5;129;01mnot[39;00m [38;5;28misinstance[39m(start, Period) [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(end, Period)):
[0;32m    560[0m     freq [38;5;241m=[39m [38;5;124m"[39m[38;5;124mD[39m[38;5;124m"[39m
[1;32m--> 562[0m data, freq [38;5;241m=[39m [43mPeriodArray[49m[38;5;241;43m.[39;49m[43m_generate_range[49m[43m([49m[43mstart[49m[43m,[49m[43m [49m[43mend[49m[43m,[49m[43m [49m[43mperiods[49m[43m,[49m[43m [49m[43mfreq[49m[43m,[49m[43m [49m[43mfields[49m[38;5;241;43m=[39;49m[43m{[49m[43m}[49m[43m)[49m
[0;32m    563[0m data [38;5;241m=[39m PeriodArray(data, freq[38;5;241m=[39mfreq)
[0;32m    564[0m [38;5;28;01mreturn[39;00m PeriodIndex(data, name[38;5;241m=[39mname)

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\core\arrays\period.py:302[0m, in [0;36mPeriodArray._generate_range[1;34m(cls, start, end, periods, freq, fields)[0m
[0;32m    298[0m     [38;5;28;01mif[39;00m field_count [38;5;241m>[39m [38;5;241m0[39m:
[0;32m    299[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    300[0m             [38;5;124m"[39m[38;5;124mCan either instantiate from fields or endpoints, but not both[39m[38;5;124m"[39m
[0;32m    301[0m         )
[1;32m--> 302[0m     subarr, freq [38;5;241m=[39m [43m_get_ordinal_range[49m[43m([49m[43mstart[49m[43m,[49m[43m [49m[43mend[49m[43m,[49m[43m [49m[43mperiods[49m[43m,[49m[43m [49m[43mfreq[49m[43m)[49m
[0;32m    303[0m [38;5;28;01melif[39;00m field_count [38;5;241m>[39m [38;5;241m0[39m:
[0;32m    304[0m     subarr, freq [38;5;241m=[39m _range_from_fields(freq[38;5;241m=[39mfreq, [38;5;241m*[39m[38;5;241m*[39mfields)

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\core\arrays\period.py:1135[0m, in [0;36m_get_ordinal_range[1;34m(start, end, periods, freq, mult)[0m
[0;32m   1132[0m     mult [38;5;241m=[39m freq[38;5;241m.[39mn
[0;32m   1134[0m [38;5;28;01mif[39;00m start [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m-> 1135[0m     start [38;5;241m=[39m [43mPeriod[49m[43m([49m[43mstart[49m[43m,[49m[43m [49m[43mfreq[49m[43m)[49m
[0;32m   1136[0m [38;5;28;01mif[39;00m end [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m   1137[0m     end [38;5;241m=[39m Period(end, freq)

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\_libs\tslibs\period.pyx:2553[0m, in [0;36mpandas._libs.tslibs.period.Period.__new__[1;34m()[0m

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\_libs\tslibs\parsing.pyx:321[0m, in [0;36mpandas._libs.tslibs.parsing.parse_time_string[1;34m()[0m

File [1;32mC:\ProgramData\Anaconda3\envs\libro-ec4301\lib\site-packages\pandas\_libs\tslibs\parsing.pyx:367[0m, in [0;36mpandas._libs.tslibs.parsing.parse_datetime_string_with_reso[1;34m()[0m

[1;31mDateParseError[0m: Unknown datetime string format, unable to parse: 2011-ABRIL
DateParseError: Unknown datetime string format, unable to parse: 2011-ABRIL

